#
# This LookML file was generated by AtScale on 2022-01-25T15:49:44.133093Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Workshop_AHR

connection: "atscale_ahr"
label: "Workshop_AHR"


include: "/views/Workshop__AHR.view.lkml"


explore: Workshop_AHR {
  label: "Workshop_AHR"
}
